MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\AToken:
  type: mappedSuperclass

  fields:
    id:
      id: true
      strategy: NONE    # id is generated because storage has to implement OAuth2\Storage\ITemporaryGenerator

    createdAt:
      type: date

    expiresAt:
      type: int # timestamp in seconds


  referenceOne:
    # client used to obtain this token
    client:
      targetEntity: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\AClient

    # user that was authenticating using client or associated with client
    user:
      targetEntity: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\AUser

  referenceMany:

    # scopes associated with this token session (they are determining user roles in system)
    scopes:
      targetEntity: MichalKvasnicak\Budle\OAuth2ServerMongoDBBundle\Document\AScope