MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Client:
  collection: oauth2_client
  type: document
  repositoryClass: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Repository\ClientRepository

  referenceMany:

    # scopes that client can access (are used in intersection with requested scopes and authenticated user scopes)
    scopes:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Scope


  referenceOne:

    # client author (if any)
    owner:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\User

