MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Client:
  collection: oauth2_client
  type: document
  repositoryClass: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Repository\ClientRepository

  fields:
    id:
      id: true

    createdAt:
      type: date

    # name of application
    name:
      type: string
      unique: true

    # if is set, client is cofidential and to use it, you have to authenticate client in grant type too
    secret:
      type: string


    redirectUri:
      type: string


    # array of allowed grant types
    grantTypes:
      type: collection


  referenceMany:

    # scopes that client can access (are used in intersection with requested scopes and authenticated user scopes)
    scopes:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Scope


  referenceOne:

    # client author (if any)
    owner:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\User

