MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\User:
  type: document
  collection: oauth2_user
  repositoryClass: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Repository\UserRepository

  referenceMany:

    # user roles (scopes) in system (what he can or can not do)
    roles:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Scope

    # client which user registered (his applications)
    clients:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Client
      mappedBy: owner
