MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\User:
  type: document
  collection: oauth2_user

  fields:
    id:
      id: true

    createdAt:
      type: date

    updatedAt:
      type: date

    username:
      type: string
      unique: true

    password:
      type: string

    salt:
      type: string

  referenceMany:

    # user roles (scopes) in system (what he can or can not do)
    roles:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Scope

    # client which user registered (his applications)
    clients:
      targetDocument: MichalKvasnicak\Bundle\OAuth2ServerMongoDBBundle\Document\Client
      mappedBy: owner

  lifecycleCallbacks:
    prePersist: [_update]
    preUpdate: [_update]
