language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.2.12
  - MONGO_VERSION=1.5.1

services:
  - mongodb

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --prefer-source
  - cp phpunit.xml.dist phpunit.xml

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v